### ISSUE TITLE
Help wanted: Is it possible to store login information in Cookies

### ISSUE THREAD

**Issue by Developer66** [adminfaces/admin-starter-security#3]
Hey,
Is is possible to save login credentials using cookies to prevent to type credentials every time?? Kind of autologin

Thanks
Developer66

**Comment by rmpestano** [comment]
Hi, 

I've just commit an example on how to do that, [see here](https://github.com/adminfaces/admin-starter-security/commit/16610a8573a2cbc3fca312a8a0219e747d26f5f4?diff=split).

You may adapt it to your needs.

I hope it helps.

**Comment by Developer66** [comment]
Wow that is beautiful and works perfect.

Only when I try to log out I get an expired.jsf error and after reload i am back at the index... I think the cookies must be deletet at logout... Is there some function to delete the login cookies?

Thanks for your help 
:)

**Comment by rmpestano** [comment]
Hi again,

now removing cookies on logout, [see here](https://github.com/adminfaces/admin-starter-security/commit/f81c5d4151b53b51b66b36d8557ee5194ed1807b).

**Comment by Developer66** [comment]
Thank you very much👍
